"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppLayout from "./AppLayout";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <Script
          type="text/javascript"
          src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=${process.env.NEXT_PUBLIC_API_KEY}`}
          onLoad={() => {
            console.log("네이버 지도 스크립트가 로드되었습니다 ✅");

            const waitForNaverMaps = setInterval(() => {
              if (window.naver && window.naver.maps) {
                console.log("✅ window.naver.maps가 준비되었습니다!");
                clearInterval(waitForNaverMaps);
                // 여기서 지도를 초기화해도 됩니다
              } else {
                console.log("⏳ window.naver.maps 대기 중...");
              }
            }, 100); // 100ms마다 체크
          }}
          onError={(e) => {
            console.error("네이버 지도 스크립트 로드 실패 ❌", e);
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
